[package]
name        = "fundb-cluster"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
thiserror.workspace  = true
anyhow.workspace     = true
tracing.workspace    = true
uuid.workspace       = true
bytes.workspace      = true

fundb-core     = { path = "../fundb-core" }
fundb-storage  = { path = "../fundb-storage" }
fundb-raft     = { path = "../fundb-raft" }
fundb-executor = { path = "../fundb-executor" }


[dev-dependencies]
proptest.workspace   = true
criterion.workspace  = true
