[package]
name        = "fundb-cognitive"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
thiserror.workspace  = true
anyhow.workspace     = true
tracing.workspace    = true
uuid                 = { workspace = true }
fundb-core           = { path = "../fundb-core" }
fundb-sql            = { path = "../fundb-sql" }
fundb-executor       = { path = "../fundb-executor" }
fundb-indexes        = { path = "../fundb-indexes" }
fundb-storage        = { path = "../fundb-storage" }


[dev-dependencies]
proptest.workspace   = true
criterion.workspace  = true
