[package]
name        = "fundb-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
thiserror.workspace  = true
anyhow.workspace     = true
tracing.workspace    = true


[dev-dependencies]
proptest.workspace   = true
criterion.workspace  = true
