[package]
name        = "fundb-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
rmp-serde.workspace  = true
thiserror.workspace  = true
anyhow.workspace     = true
tracing.workspace    = true
bytes.workspace      = true
xxhash-rust          = { workspace = true }
zstd.workspace       = true
fundb-core           = { path = "../fundb-core" }


[dev-dependencies]
proptest.workspace   = true
criterion.workspace  = true
uuid.workspace       = true
tempfile             = "3"
