[package]
name        = "fundb-optimizer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
thiserror.workspace  = true
anyhow.workspace     = true
tracing.workspace    = true
fundb-core           = { path = "../fundb-core" }
fundb-sql            = { path = "../fundb-sql" }


[dev-dependencies]
proptest.workspace   = true
criterion.workspace  = true
